service:
  name: stasisgg-backend

package:
  individually: false
  excludeDevDependencies: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline
  - serverless-dotenv-plugin

provider:
  name: aws
  runtime: nodejs12.x
  region: ap-northeast-1
  environment:
    RIOT_LOL_API_KEY: ${env:RIOT_LOL_API_KEY}

layers:
  axios:
    package:
      artifact: layers/axios/axios.zip
  kayn:
    package:
      artifact: layers/kayn/kayn.zip
  twisted:
    package:
      artifact: layers/twisted/twisted.zip

functions:
  get-one-match-card:
    handler: src/get-one-match-card/getOneMatchCard.getOneMatchCard
    events:
      - http:
          method: get
          path: get-one-match-card
          cors: true
    layers:
      - { Ref: AxiosLambdaLayer }
      - { Ref: KaynLambdaLayer }

  get-player-profile:
    handler: src/get-player-profile/getPlayerProfile.getPlayerProfile
    events:
      - http:
          method: get
          path: get-player-profile
          cors: true
    layers:
      - { Ref: AxiosLambdaLayer }
      - { Ref: KaynLambdaLayer }

  get-matches:
    handler: src/get-matches/getMatchesHandler.getMatchesHandler
    events:
      - http:
          method: get
          path: get-matches
          cors: true
    layers:
      - { Ref: AxiosLambdaLayer }
      - { Ref: TwistedLambdaLayer }