on:
  push:
    branches:
      - release
name: Deploy release branch
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: Install Dependencies
      run: |
        yarn add serverless
        yarn install
    - name: Test
      run: yarn test-all
    - name: serverless deploy
      run: yarn deploy
      env:
        RIOT_LOL_API_KEY: ${{ secrets.RIOT_LOL_API_KEY}}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}