name: Build and Test
on: [push]

jobs:
  build:
    name: Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1.1.0
        with:
          node-version: '10.x'
      - run: yarn install
      - run: yarn test